spring.application.name=Coursework_Deadline_Optimiser
spring.jpa.hibernate.ddl-auto=validate
spring.profiles.active=prod

jwt.secret=f3a9c2e7b1d4f6a8c0e2b4d6f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6
jwt.expiration=86400000